"""
NyayaBot — Export summary card endpoint.
"""
from __future__ import annotations

import logging
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel, Field

from src.api.security import require_admin

from src.models import Citation

logger = logging.getLogger(__name__)
router = APIRouter()

class ExportCardRequest(BaseModel):
    query: str = Field(max_length=2000)
    answer: str = Field(max_length=20000)
    citations: List[Citation] = Field(max_length=30)
    legal_standing_score: float
    route: str = Field(max_length=40)
    session_id: str = Field(max_length=100)

@router.post("/export/card", dependencies=[Depends(require_admin)])
async def export_legal_card(request: ExportCardRequest):
    """
    Generate a downloadable legal summary card in Markdown format.
    """
    try:
        # Determine standing label
        score = request.legal_standing_score
        if score >= 80:
            standing_label = f"🟢 Strong Legal Standing ({score}/100)"
            standing_desc = "The law is clearly on your side. The retrieved statutes and/or precedents strongly support your position."
        elif score >= 50:
            standing_label = f"🟡 Moderate Legal Standing ({score}/100)"
            standing_desc = "You have reasonable legal standing, but the situation contains nuances or depends on specific facts."
        else:
            standing_label = f"🔴 Uncertain Legal Standing ({score}/100)"
            standing_desc = "Your legal position is unverified or lacks strong RAG grounding. We highly recommend verifying with an advocate."

        # Format citations
        citations_md = ""
        if request.citations:
            citations_md = "\n".join(
                f"- **{c.document_title}** (Section: {c.section or 'N/A'})"
                for c in request.citations
            )
        else:
            citations_md = "*No specific statutory citations were grounded for this response.*"

        # Generate markdown card
        card_content = f"""# 📋 Vidhi Legal Summary Card
--------------------------------------------------
**Legal Guardian in Your Pocket** 🇮🇳
--------------------------------------------------

### 🔍 SITUATION / QUERY
> {request.query}

### ⚖️ LEGAL STANDING SCORE
**{standing_label}**
{standing_desc}

### 📜 KEY CITATIONS & AUTHORITIES
{citations_md}

### 💡 DETAILED GUIDANCE SUMMARY
{request.answer}

--------------------------------------------------
⚠️ **OFFICIAL DISCLAIMER**
This card is generated by Vidhi based on retrieved Indian law documents. It is for general information and educational purposes only. This does NOT constitute formal legal advice. Please verify with a licensed advocate or official gazette notifications before taking legal action.
--------------------------------------------------
Generated by Vidhi | Session: {request.session_id}
"""

        # Return as downloadable attachment
        headers = {
            "Content-Disposition": "attachment; filename=vidhi_legal_card.md"
        }
        return Response(
            content=card_content,
            media_type="text/markdown",
            headers=headers
        )

    except Exception as e:
        logger.error(f"Error exporting card: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to generate card")
